# Seminar 1
### Walkthrough

Put the data files in the same folder as your Jupyter Notebook files if there are data files. 
We learn coding by imitation. Therefore, we start by copying example codes and run them. Based on the outputs, comments, and the codes, we understand what the codes need and what the codes produce. Then we can modify the codes and apply them to new data for solving new problems.

1. Install Python and learn about Jupyter Notebook by reading the materials.

2. Try basic Python operations: Start a new Jupyter Notebook and copy the following codes one (line/part) by one, followed by press the keys Shift + Enter.

Python Basics

This file helps you review basic Python operations. You can learn more details on a free e-book 

https://problemsolvingwithpython.com/

In [1]:
# Lists

an_empty_list = list()
an_empty_list

a_list = [1, 2.3, 'a', True]
a_list

a_list[1] 


2.3

In [2]:
a_list[1] = 2.5
# a_list is now [1, 2.5, 'a', True]
a_list


a_list[1:3]


[2.5, 'a']

In [3]:
a_list[1:4]

a_list[2:3]

a_list[::-1] 


[True, 'a', 2.5, 1]

In [4]:
a_list.append(5) 
# a_list is now [1, 2.5, 'a', True, 5]
a_list

len(a_list) 


5

In [5]:
del a_list[0] 
# a_list is now [2.5, 'a', True, 5]
a_list

a_list += [1, 'b'] 
# a_list is now [2.5, 'a', True, 5, 1, 'b']
a_list 


[2.5, 'a', True, 5, 1, 'b']

### Defining Functions

In [9]:
def half(x): 
    return x/2.0

half(10) 

half(18) 

half(29) 

half(12345) 

6172.5

# Numpy for Matrix operations

In [10]:
## Numpy for arrays and numerical operations et cetera

import numpy as np


In [11]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
a.shape

(3, 5)

In [15]:
a.ndim

2

In [16]:
a.size

15

In [17]:
c=np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
d=np.ones((2, 3, 4))
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
a.min()

0

In [20]:
a.sum()

105

In [21]:
a.max()

14

In [22]:
a[0]

array([0, 1, 2, 3, 4])

In [23]:
a[1]

array([5, 6, 7, 8, 9])

In [24]:
a[2]

array([10, 11, 12, 13, 14])

# Data obtention & processing

Get company stock data: Start a new Jupyter Notebook and copy the following codes one (line/part) by one, followed by press the keys Shift + Enter.

In [25]:
# Get company stock data
# This cell is only needed to be run once.

! pip install yahooquery

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 2.3 MB/s eta 0:00:0000:0100:01m
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 1.1 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 4.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 5.8 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 2.4 MB/s eta 0:00:0000:0100:01
  Created wheel for lxml: filename=lxml-4.9.3-cp39-cp39-macosx_10_9_x86_64.whl size=1735108 sha256=729311936c1be39f4a8e8a8b63a4a21b7436b2e44874032bd3fabfd272a50686
  Stored in directory: /Users/HectorEnc/Library/Caches/pip/wheels/5c/05/aa/530f84480d476c5bb9ea09877eea78fb144ec047fbb00ee2ca
Successfully built lxml
  Attempting uninstall: tqdm
    Found existi

In [29]:
aapl = Ticker('aapl')

NameError: name 'Ticker' is not defined